# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Snake_config = debug
endif
ifeq ($(config),release)
  Snake_config = release
endif

PROJECTS := Snake

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Snake:
ifneq (,$(Snake_config))
	@echo "==== Building Snake ($(Snake_config)) ===="
	@${MAKE} --no-print-directory -C . -f Snake.make config=$(Snake_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Snake.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Snake"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"